### ISSUE TITLE
TODO: export result as CSV

### ISSUE THREAD

**Issue by guillim** [guillim/Arachnida#1]
A feature to enables downloading results when crawler has finished

**Comment by navansingh** [comment]
Hey @guillim, is this project still alive and looking for help on this feature?

**Comment by guillim** [comment]
Hi,
Yes, this project is still alive. I have to say I haven't opened it up for a couple months though. But I will do again if you're willing to contribute !!!

**Comment by navansingh** [comment]
Yes, sounds like this feature is easy enough to start things off. Do you have a specific way in mind for doing this?

**Comment by guillim** [comment]
Nothing in mind, feel free to choose your way

**Comment by navansingh** [comment]
Got it. I will create a PR in the coming weeks. Thanks!

**Comment by MemoVDG** [comment]
Is this issue still open?

**Comment by guillim** [comment]
It is yes

**Comment by clariokids** [comment]
you can check on #4 
as there is no clear about design, i try to follow existing one theme
as for "result", my perspective is on 1 detail crawl result table
